#!/bin/bash
set -e
cd /usr/share/amongus
ANDROID_AVD_HOME=/usr/share/amongus/avd ANDROID_SDK_ROOT=/usr/share/amongus/sdk sdk/emulator/emulator -avd amongus -no-snapshot &

adb wait-for-device
while [ "$(adb shell getprop sys.boot_completed | tr -d '\r')" != "1" ]
do
	sleep 2
done

if ! adb shell pm list packages | grep com.wparam.nullkeyboard
then
	adb install /usr/share/amongus/nullkeyboard.apk
	sleep 5
	adb shell ime enable com.wparam.nullkeyboard/.NullKeyboard
	adb shell ime set com.wparam.nullkeyboard/.NullKeyboard
fi
python3 /usr/share/amongus/amongus.py /tmp/amongus.apk
adb install /tmp/amongus.apk
rm /tmp/amongus.apk
adb shell am start -n com.innersloth.spacemafia/com.unity3d.player.UnityPlayerActivity
for (( i=0; i<10; ++i))
do
  adb shell input keyevent 24
done

keyboard2mouse /usr/share/amongus/controls.ini
